size                          = "Standard_B1s"
caching                       = "ReadWrite"
storage_account_type          = "Standard_LRS"
allocation_method             = "Dynamic"
private_ip_address_allocation = "Dynamic"
size_honeypot                 = "Standard_B2ms"